module.exports = {
    roles: ["student", "landlord", "admin", "super_admin", "manager"],
    signin_roles: ["student", "landlord"],
    activitiesTypes: [
        "login",
        "logout",
        "dashboard_viewed",
        "application_approved",
        "application_rejected",
        "payment_received",
        "payment_released",
    ],
    living_status: ["alone", "with_family"],
    gender: ["male", "female"],
    propertyTypes: ["flat", "room"],
    propertyStates: ["drafted", "sent", "approved", "declined"],
    propertyStateTransitions: {
        submitDrafted: { from: "drafted", to: "sent" },
        approveSent: { from: "sent", to: "approved" },
        declineSent: { from: "sent", to: "declined" },
        reopenDeclined: { from: "declined", to: "sent" },
    },
    applicationStatus: ['pending', 'approved', 'paid','checked_in', 'rejected', 'completed'],
    paymentStatus: ['pending', 'received', 'released', 'refunded'],
    paymentMethods: ['card', 'wallet', 'cash', 'transfer'],
    APP_STATUS: {
        PENDING: 'pending',
        APPROVED: 'approved',
        REJECTED: 'rejected',
        PAID: 'paid',
        CHECKED_IN: 'checked_in',
        COMPLETED: 'completed',
    },
    currency:["EGP","USD"]
};