const { uuids, SEED_PASSWORD, daysAgo, daysFromNow } = require('./helpers');

const users = [
  { key: 'student1', username: 'student1', email: 'student1@sakan.test', phone: '01000000001', countryCode: '+20', role: 'student' },
  { key: 'student2', username: 'student2', email: 'student2@sakan.test', phone: '01000000002', countryCode: '+20', role: 'student' },
  { key: 'student3', username: 'student3', email: 'student3@sakan.test', phone: '01000000003', countryCode: '+20', role: 'student' },
  { key: 'landlord1', username: 'landlord1', email: 'landlord1@sakan.test', phone: '01100000001', countryCode: '+20', role: 'landlord' },
  { key: 'landlord2', username: 'landlord2', email: 'landlord2@sakan.test', phone: '01100000002', countryCode: '+20', role: 'landlord' },
  { key: 'landlord3', username: 'landlord3', email: 'landlord3@sakan.test', phone: '01100000003', countryCode: '+20', role: 'landlord' },
  { key: 'admin1', username: 'admin1', email: 'admin1@sakan.test', phone: '01200000001', countryCode: '+20', role: 'admin' },
  { key: 'admin2', username: 'admin2', email: 'admin2@sakan.test', phone: '01200000002', countryCode: '+20', role: 'admin' },
  { key: 'admin3', username: 'admin3', email: 'admin3@sakan.test', phone: '01200000003', countryCode: '+20', role: 'admin' },
  { key: 'superadmin1', username: 'superadmin1', email: 'superadmin1@sakan.test', phone: '01300000001', countryCode: '+20', role: 'super_admin' },
  { key: 'superadmin2', username: 'superadmin2', email: 'superadmin2@sakan.test', phone: '01300000002', countryCode: '+20', role: 'super_admin' },
  { key: 'superadmin3', username: 'superadmin3', email: 'superadmin3@sakan.test', phone: '01300000003', countryCode: '+20', role: 'super_admin' },
  { key: 'manager1', username: 'manager1', email: 'manager1@sakan.test', phone: '01400000001', countryCode: '+20', role: 'manager' },
  { key: 'manager2', username: 'manager2', email: 'manager2@sakan.test', phone: '01400000002', countryCode: '+20', role: 'manager' },
  { key: 'manager3', username: 'manager3', email: 'manager3@sakan.test', phone: '01400000003', countryCode: '+20', role: 'manager' },
].map((u) => ({
  ...u,
  id: uuids.user(u.key),
  password_hash: SEED_PASSWORD,
  verified: true,
}));

const profiles = [
  { key: 'student1', userId: uuids.user('student1'), firstName: 'Omar', lastName: 'Hassan', bio: 'Final year CS student at Cairo University, looking for a quiet place near campus.', university: 'Cairo University', gender: 'male', studyField: 'Computer Science', living_status: 'alone', budget: 4000, location: 'Dokki, Giza' },
  { key: 'student2', userId: uuids.user('student2'), firstName: 'Sara', lastName: 'Mostafa', bio: 'Medicine student who enjoys cooking and reading.', university: 'Ain Shams University', gender: 'female', studyField: 'Medicine', living_status: 'with_family', budget: 6000, location: 'Zamalek, Cairo' },
  { key: 'student3', userId: uuids.user('student3'), firstName: 'Khaled', lastName: 'Adel', bio: 'Engineering student, tidy and social.', university: 'Cairo University', gender: 'male', studyField: 'Engineering', living_status: 'alone', budget: 3000, location: 'Nasr City, Cairo' },
  { key: 'landlord1', userId: uuids.user('landlord1'), firstName: 'Ahmed', lastName: 'Samir', bio: 'Landlord with several student flats in Dokki and Zamalek.', gender: 'male', living_status: 'with_family', location: 'Dokki, Giza' },
  { key: 'landlord2', userId: uuids.user('landlord2'), firstName: 'Mona', lastName: 'Fathy', bio: 'Owns shared student housing in Nasr City and Mohandessin.', gender: 'female', living_status: 'with_family', location: 'Nasr City, Cairo' },
  { key: 'landlord3', userId: uuids.user('landlord3'), firstName: 'Tarek', lastName: 'Nabil', bio: 'Landlord focused on furnished apartments near universities.', gender: 'male', living_status: 'with_family', location: 'New Cairo' },
  { key: 'admin1', userId: uuids.user('admin1'), firstName: 'Youssef', lastName: 'Kamal', bio: 'Platform admin.', gender: 'male', living_status: 'with_family' },
  { key: 'admin2', userId: uuids.user('admin2'), firstName: 'Nour', lastName: 'Ali', bio: 'Platform admin.', gender: 'female', living_status: 'with_family' },
  { key: 'admin3', userId: uuids.user('admin3'), firstName: 'Hana', lastName: 'Mahmoud', bio: 'Platform admin.', gender: 'female', living_status: 'with_family' },
  { key: 'superadmin1', userId: uuids.user('superadmin1'), firstName: 'Omar', lastName: 'Sherif', bio: 'Super admin.', gender: 'male', living_status: 'with_family' },
  { key: 'superadmin2', userId: uuids.user('superadmin2'), firstName: 'Laila', lastName: 'Osman', bio: 'Super admin.', gender: 'female', living_status: 'with_family' },
  { key: 'superadmin3', userId: uuids.user('superadmin3'), firstName: 'Karim', lastName: 'Fouad', bio: 'Super admin.', gender: 'male', living_status: 'with_family' },
  { key: 'manager1', userId: uuids.user('manager1'), firstName: 'Salma', lastName: 'Ibrahim', bio: 'Platform manager.', gender: 'female', living_status: 'with_family' },
  { key: 'manager2', userId: uuids.user('manager2'), firstName: 'Mohamed', lastName: 'Tarek', bio: 'Platform manager.', gender: 'male', living_status: 'with_family' },
  { key: 'manager3', userId: uuids.user('manager3'), firstName: 'Yara', lastName: 'Adel', bio: 'Platform manager.', gender: 'female', living_status: 'with_family' },
].map((p) => ({
  ...p,
  id: uuids.profile(p.key),
}));

const preferences = [
  { key: 'student1', userId: uuids.user('student1'), theme: 'light', notification: true, language: 'en' },
  { key: 'student2', userId: uuids.user('student2'), theme: 'dark', notification: true, language: 'en' },
  { key: 'student3', userId: uuids.user('student3'), theme: 'light', notification: true, language: 'en' },
  { key: 'landlord1', userId: uuids.user('landlord1'), theme: 'light', notification: true, language: 'en' },
  { key: 'landlord2', userId: uuids.user('landlord2'), theme: 'light', notification: true, language: 'en' },
  { key: 'landlord3', userId: uuids.user('landlord3'), theme: 'dark', notification: true, language: 'en' },
  { key: 'admin1', userId: uuids.user('admin1'), theme: 'light', notification: true, language: 'en' },
  { key: 'admin2', userId: uuids.user('admin2'), theme: 'light', notification: true, language: 'en' },
  { key: 'admin3', userId: uuids.user('admin3'), theme: 'dark', notification: true, language: 'en' },
  { key: 'superadmin1', userId: uuids.user('superadmin1'), theme: 'light', notification: true, language: 'en' },
  { key: 'superadmin2', userId: uuids.user('superadmin2'), theme: 'light', notification: true, language: 'en' },
  { key: 'superadmin3', userId: uuids.user('superadmin3'), theme: 'dark', notification: true, language: 'en' },
  { key: 'manager1', userId: uuids.user('manager1'), theme: 'light', notification: true, language: 'en' },
  { key: 'manager2', userId: uuids.user('manager2'), theme: 'light', notification: true, language: 'en' },
  { key: 'manager3', userId: uuids.user('manager3'), theme: 'dark', notification: true, language: 'en' },
].map((p) => ({
  ...p,
  id: uuids.preference(p.key),
}));

const properties = [
  {
    key: 'p1',
    title: 'Modern 2BR Flat in Dokki',
    description: 'A bright and fully furnished two-bedroom flat close to Cairo University. Quiet street, fast internet, and utilities included in the rent.',
    images: [],
    pricePerMonth: 4500,
    totalRooms: 3,
    availableRooms: 2,
    type: 'flat',
    locationLat: 30.0369,
    locationLong: 31.2087,
    address: '12 Tahrir St, Dokki, Giza',
    amenities: { wifi: true, furnished: true, kitchen: true, elevator: true, utilitiesIncluded: true },
    userId: uuids.user('landlord1'),
    isActive: true,
    state: 'approved',
  },
  {
    key: 'p2',
    title: 'Cozy Studio in Zamalek',
    description: 'Compact studio in the heart of Zamalek with a small balcony. Fully furnished and ready for immediate move-in.',
    images: [],
    pricePerMonth: 6000,
    totalRooms: 2,
    availableRooms: 1,
    type: 'flat',
    locationLat: 30.0638,
    locationLong: 31.216,
    address: '8 Brazil St, Zamalek, Cairo',
    amenities: { wifi: true, furnished: true, kitchen: true, ac: true },
    userId: uuids.user('landlord1'),
    isActive: true,
    state: 'approved',
  },
  {
    key: 'p3',
    title: 'Student Flat in Nasr City',
    description: 'Spacious flat shared by students, close to metro and university campuses. Includes a study room.',
    images: [],
    pricePerMonth: 3500,
    totalRooms: 4,
    availableRooms: 3,
    type: 'flat',
    locationLat: 30.0649,
    locationLong: 31.2474,
    address: '5 Abbas El Akkad St, Nasr City, Cairo',
    amenities: { wifi: true, furnished: true, kitchen: true, studyRoom: true },
    userId: uuids.user('landlord2'),
    isActive: true,
    state: 'sent',
  },
  {
    key: 'p4',
    title: 'Shared Room in Mohandessin',
    description: 'Private room in a shared flat in Mohandessin, minutes from shops and cafes. Desk and wardrobe included.',
    images: [],
    pricePerMonth: 2500,
    totalRooms: 2,
    availableRooms: 1,
    type: 'room',
    locationLat: 30.0477,
    locationLong: 31.2138,
    address: '22 Gameat El Dowal, Mohandessin, Giza',
    amenities: { wifi: true, desk: true },
    userId: uuids.user('landlord2'),
    isActive: true,
    state: 'approved',
  },
  {
    key: 'p5',
    title: 'Apartment near AUC',
    description: 'Furnished apartment in New Cairo near AUC campus with parking and a small gym.',
    images: [],
    pricePerMonth: 8000,
    totalRooms: 3,
    availableRooms: 3,
    type: 'flat',
    locationLat: 30.0193,
    locationLong: 31.4998,
    address: 'New Cairo, Cairo',
    amenities: { wifi: true, furnished: true, parking: true, gym: true },
    userId: uuids.user('landlord3'),
    isActive: false,
    state: 'drafted',
  },
  {
    key: 'p6',
    title: 'Room in 6th October',
    description: 'Large room in a family building in 6th October City, near the university gates.',
    images: [],
    pricePerMonth: 5000,
    totalRooms: 2,
    availableRooms: 2,
    type: 'room',
    locationLat: 29.9366,
    locationLong: 30.9177,
    address: '6th October City, Giza',
    amenities: { wifi: true, furniture: true },
    userId: uuids.user('landlord3'),
    isActive: true,
    state: 'declined',
  },
].map((p) => ({
  ...p,
  id: uuids.property(p.key),
}));

const applications = [
  {
    key: 'app1',
    userId: uuids.user('student1'),
    propertyId: uuids.property('p1'),
    isForSharing: false,
    message: 'I am a final year CS student looking for a quiet flat near campus.',
    totalAmount: 4500,
    status: 'completed',
    approvedBy: uuids.user('admin1'),
    approvedAt: daysAgo(20),
    approvalExpiresAt: daysAgo(19),
    paidAt: daysAgo(19),
    checkedInAt: daysAgo(18),
    completedAt: daysAgo(10),
  },
  {
    key: 'app2',
    userId: uuids.user('student2'),
    propertyId: uuids.property('p2'),
    isForSharing: false,
    message: 'I would love to move into the Zamalek studio this month.',
    totalAmount: 6000,
    status: 'checked_in',
    approvedBy: uuids.user('admin1'),
    approvedAt: daysAgo(8),
    approvalExpiresAt: daysAgo(7),
    paidAt: daysAgo(7),
    checkedInAt: daysAgo(5),
  },
  {
    key: 'app3',
    userId: uuids.user('student3'),
    propertyId: uuids.property('p4'),
    isForSharing: false,
    message: 'I liked this room, happy to proceed.',
    totalAmount: 2500,
    status: 'approved',
    approvedBy: uuids.user('admin1'),
    approvedAt: daysAgo(1),
    approvalExpiresAt: daysFromNow(1),
  },
  {
    key: 'app4',
    userId: uuids.user('student2'),
    propertyId: uuids.property('p4'),
    isForSharing: false,
    message: 'Sorry, the room has already been taken by another applicant.',
    totalAmount: 2500,
    status: 'rejected',
  },
  {
    key: 'app5',
    userId: uuids.user('student1'),
    propertyId: uuids.property('p2'),
    isForSharing: false,
    message: 'Is it possible to move in next week?',
    totalAmount: 6000,
    status: 'pending',
  },
  {
    key: 'app6',
    userId: uuids.user('student3'),
    propertyId: uuids.property('p1'),
    isForSharing: false,
    message: 'I would like to apply for this flat.',
    totalAmount: 4500,
    status: 'pending',
  },
].map((a) => ({
  ...a,
  id: uuids.application(a.key),
}));

const payments = [
  {
    key: 'pay1',
    applicationId: uuids.application('app1'),
    studentId: uuids.user('student1'),
    landlordId: uuids.user('landlord1'),
    amount: 4500,
    status: 'released',
    method: 'card',
    currency: 'EGP',
    receivedAt: daysAgo(19),
    receivedBy: uuids.user('admin1'),
    releasedAt: daysAgo(12),
    releasedBy: uuids.user('admin1'),
  },
  {
    key: 'pay2',
    applicationId: uuids.application('app2'),
    studentId: uuids.user('student2'),
    landlordId: uuids.user('landlord1'),
    amount: 6000,
    status: 'received',
    method: 'wallet',
    currency: 'EGP',
    receivedAt: daysAgo(5),
    receivedBy: uuids.user('admin1'),
  },
  {
    key: 'pay3',
    applicationId: uuids.application('app3'),
    studentId: uuids.user('student3'),
    landlordId: uuids.user('landlord2'),
    amount: 2500,
    status: 'pending',
    method: 'card',
    currency: 'EGP',
  },
].map((p) => ({
  ...p,
  id: uuids.payment(p.key),
}));

const flatmateRequests = [
  {
    key: 'fmr1',
    userId: uuids.user('student1'),
    preferredBudget: 4000,
    preferredType: 'flat',
    message: 'Looking for a flatmate to share a 2BR in Nasr City.',
    peopleWanted: 1,
    radiusKm: 5,
    locationLat: 30.0649,
    locationLong: 31.2474,
    isMatched: true,
  },
  {
    key: 'fmr2',
    userId: uuids.user('student2'),
    preferredBudget: 3500,
    preferredType: 'flat',
    message: 'Need two flatmates for a big flat in Dokki.',
    peopleWanted: 2,
    radiusKm: 10,
    locationLat: 30.0369,
    locationLong: 31.2087,
    isMatched: false,
  },
  {
    key: 'fmr3',
    userId: uuids.user('student3'),
    preferredBudget: 3200,
    preferredType: 'flat',
    message: 'Looking to share a flat near Mohandessin.',
    peopleWanted: 1,
    radiusKm: 8,
    locationLat: 30.0477,
    locationLong: 31.2138,
    isMatched: false,
  },
].map((r) => ({
  ...r,
  id: uuids.flatmateRequest(r.key),
}));

const joinInterests = [
  {
    key: 'ji1',
    requesterId: uuids.user('student3'),
    flatmateRequestId: uuids.flatmateRequest('fmr1'),
    message: 'I am interested in joining, I am a quiet student.',
    status: 'accepted',
  },
  {
    key: 'ji2',
    requesterId: uuids.user('student3'),
    flatmateRequestId: uuids.flatmateRequest('fmr2'),
    message: 'Would love to join your flat hunt.',
    status: 'pending',
  },
  {
    key: 'ji3',
    requesterId: uuids.user('student1'),
    flatmateRequestId: uuids.flatmateRequest('fmr2'),
    message: 'Hi, I am looking for a flat in Dokki too.',
    status: 'pending',
  },
  {
    key: 'ji4',
    requesterId: uuids.user('student1'),
    flatmateRequestId: uuids.flatmateRequest('fmr3'),
    message: 'Let me know if you find a place.',
    status: 'rejected',
  },
].map((i) => ({
  ...i,
  id: uuids.joinInterest(i.key),
}));

const propertyRequests = [
  {
    key: 'pr1',
    userId: uuids.user('student1'),
    message: 'Looking for a 2-bedroom flat near Cairo University for the next semester.',
    propertyType: 'flat',
    requestType: 'looking',
    phone: '01000000001',
    address: 'Giza',
    major: 'Computer Science',
    status: 'contacted',
  },
  {
    key: 'pr2',
    userId: uuids.user('student2'),
    message: 'Offering a furnished room in a shared flat in Zamalek.',
    propertyType: 'room',
    requestType: 'offering',
    phone: '01000000002',
    address: 'Zamalek, Cairo',
    status: 'resolved',
  },
  {
    key: 'pr3',
    userId: uuids.user('student3'),
    message: 'Looking for an affordable room near Ain Shams University.',
    propertyType: 'room',
    requestType: 'looking',
    phone: '01000000003',
    address: 'Ain Shams, Cairo',
    status: 'pending',
  },
  {
    key: 'pr4',
    userId: uuids.user('landlord1'),
    message: 'Offering a newly renovated flat for students in Dokki.',
    propertyType: 'flat',
    requestType: 'offering',
    phone: '01100000001',
    address: 'Dokki, Giza',
    status: 'pending',
  },
].map((r) => ({
  ...r,
  id: uuids.propertyRequest(r.key),
}));

const chats = [
  { key: 'chat1', user1_id: uuids.user('student1'), user2_id: uuids.user('landlord1'), last_message: 'See you this weekend then.' },
  { key: 'chat2', user1_id: uuids.user('student2'), user2_id: uuids.user('landlord1'), last_message: 'The lease is ready for you.' },
  { key: 'chat3', user1_id: uuids.user('student3'), user2_id: uuids.user('landlord2'), last_message: 'Great, I will confirm the room today.' },
].map((c) => ({
  ...c,
  id: uuids.chat(c.key),
}));

const messages = [
  { key: 'msg1', sender_id: uuids.user('student1'), chat_id: uuids.chat('chat1'), message: 'Hi, is the Dokki flat still available?' },
  { key: 'msg2', sender_id: uuids.user('landlord1'), chat_id: uuids.chat('chat1'), message: 'Yes it is, would you like to schedule a visit?' },
  { key: 'msg3', sender_id: uuids.user('student1'), chat_id: uuids.chat('chat1'), message: 'This weekend works for me.' },
  { key: 'msg4', sender_id: uuids.user('landlord1'), chat_id: uuids.chat('chat1'), message: 'See you this weekend then.' },
  { key: 'msg5', sender_id: uuids.user('student2'), chat_id: uuids.chat('chat2'), message: 'Hello, I would like to move into the Zamalek studio.' },
  { key: 'msg6', sender_id: uuids.user('landlord1'), chat_id: uuids.chat('chat2'), message: 'Sure, the lease is ready for you.' },
  { key: 'msg7', sender_id: uuids.user('student3'), chat_id: uuids.chat('chat3'), message: 'Is the room in Mohandessin still free?' },
  { key: 'msg8', sender_id: uuids.user('landlord2'), chat_id: uuids.chat('chat3'), message: 'Great, I will confirm the room today.' },
].map((m) => ({
  ...m,
  id: uuids.message(m.key),
}));

const notifications = [
  { userId: uuids.user('student1'), notificationType: 'application_approved', notificationContent: { title: 'Application approved', body: 'Your application for Modern 2BR Flat in Dokki was approved.' }, read: true },
  { userId: uuids.user('student1'), notificationType: 'payment_released', notificationContent: { title: 'Payment released', body: 'Your deposit has been released for settlement.' }, read: false },
  { userId: uuids.user('student2'), notificationType: 'payment_received', notificationContent: { title: 'Payment received', body: 'Your payment has been confirmed by Sakan Support.' }, read: false },
  { userId: uuids.user('student3'), notificationType: 'application_approved', notificationContent: { title: 'Application approved', body: 'Your application for Shared Room in Mohandessin was approved.' }, read: false },
  { userId: uuids.user('landlord1'), notificationType: 'application_completed', notificationContent: { title: 'Application completed', body: 'A student has completed the rental flow for your property.' }, read: false },
  { userId: uuids.user('landlord1'), notificationType: 'payment_released', notificationContent: { title: 'Payout released', body: 'A payout has been released for one of your received payments.' }, read: true },
  { userId: uuids.user('landlord2'), notificationType: 'application_approved', notificationContent: { title: 'Application approved', body: 'A student application was approved for your property.' }, read: false },
  { userId: uuids.user('admin1'), notificationType: 'application_pending', notificationContent: { title: 'New application', body: 'A new application is waiting for your review.' }, read: false },
];

const activities = [
  { userId: uuids.user('admin1'), activityType: 'application_approved', activityDetails: { entityType: 'application', entityId: uuids.application('app1'), applicationId: uuids.application('app1') } },
  { userId: uuids.user('admin1'), activityType: 'payment_received', activityDetails: { entityType: 'payment', entityId: uuids.payment('pay2'), paymentId: uuids.payment('pay2') } },
  { userId: uuids.user('admin1'), activityType: 'payment_released', activityDetails: { entityType: 'payment', entityId: uuids.payment('pay1'), paymentId: uuids.payment('pay1') } },
  { userId: uuids.user('admin1'), activityType: 'dashboard_viewed', activityDetails: {} },
  { userId: uuids.user('student1'), activityType: 'login', activityDetails: { method: 'password' } },
  { userId: uuids.user('student2'), activityType: 'login', activityDetails: { method: 'password' } },
  { userId: uuids.user('landlord1'), activityType: 'login', activityDetails: { method: 'password' } },
];

module.exports = {
  users,
  profiles,
  preferences,
  properties,
  applications,
  payments,
  flatmateRequests,
  joinInterests,
  propertyRequests,
  chats,
  messages,
  notifications,
  activities,
};
